.github/workflows/check-deps.yml
.github/workflows/ci.yml
.gitignore
pom.xml

As part of setting up the HSC dev server, we need to set up the GA pipelines for this project https://mekomsolutions.atlassian.net/browse/HSC-260

HSC-260: Add GA CI pipeline

---

configs/openmrs/frontend_config/ozone-frontend-config.json
configs/openmrs/initializer_config/ampathforms/anthropometric_measure_1.json
configs/openmrs/initializer_config/ampathforms/emergency_followup.json
configs/openmrs/initializer_config/ampathforms/gynecology_ultrasound.json
configs/openmrs/initializer_config/ampathforms/mode_of_arrival_1.json
configs/openmrs/initializer_config/ampathforms/obstetrics_ultrasound_2.json
configs/openmrs/initializer_config/ampathforms/obstetrics_ultrasound_3.json
configs/openmrs/initializer_config/ampathforms/physical_examination_1.json
configs/openmrs/initializer_config/ampathforms/referral.json
configs/openmrs/initializer_config/ampathforms/triage.json
pom.xml

Ticket:https://mekomsolutions.atlassian.net/browse/HSC-287

HSC-287: Configured Clinical Forms

---

configs/openmrs/initializer_config/liquibase/liquibase.xml

Ticket: https://mekomsolutions.atlassian.net/browse/HSC-300

HSC-300: Fixed email person attribute uuid.

---

configs/openmrs/initializer_config/concepts/registration.csv

Ticket: https://mekomsolutions.atlassian.net/browse/HSC-285

HSC-285: Capture patient photo feature to work as expected.

---

configs/openmrs/frontend_config/ozone-frontend-config.json

https://mekomsolutions.atlassian.net/browse/HSC-281

HSC-281: Added `dateAndTimeOfDeath` to death fields

---

configs/openmrs/initializer_config/attributetypes/id_prefix.csv
configs/openmrs/initializer_config/autogenerationoptions/autogenerationoptions.csv
configs/openmrs/initializer_config/idgen/identifierSource.csv

Ticket here: https://mekomsolutions.atlassian.net/browse/HSC-281?focusedCommentId=45171

HSC-281: Fixed identifier Numéro Dossier

---

configs/openmrs/frontend_config/ozone-frontend-config.json
configs/openmrs/initializer_config/ampathforms/anthropometric_measure_1.json
configs/openmrs/initializer_config/ampathforms/vitalsAndBiometrics.json

Ticket: https://mekomsolutions.atlassian.net/browse/HSC-288

HSC-288: Fixed Weight and Height UUIDs + added range validations.

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Ticket: https://mekomsolutions.atlassian.net/browse/HSC-338

HSC-338: Configured attachments-overview-widget as part of patient summary dashboard

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Link to the ticket: https://mekomsolutions.atlassian.net/browse/HSC-346

HSC-346: Do not display the `Mode of arrival` visit attribute on the patient banner

---

configs/openmrs/initializer_config/autogenerationoptions/autogenerationoptions.csv

Ticket:https://mekomsolutions.atlassian.net/browse/HSC-347

HSC-347: Disable manual entry for Numero Dossier

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Ticket:https://mekomsolutions.atlassian.net/browse/HSC-348

HSC-348: Added allergies-overview-widget to patient summary dashboard

---

configs/openmrs/frontend_config/ozone-frontend-config.json
configs/openmrs/initializer_config/ampathforms/vitalsAndBiometrics.json

Ticket here: https://mekomsolutions.atlassian.net/browse/HSC-337

HSC-337: Moved Triage from visit attributes to Vitals and Biometrics

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Ticket here: https://mekomsolutions.atlassian.net/browse/HSC-352

HSC-352: Fix contact and address information in patient banner

---

configs/openmrs/frontend_config/ozone-frontend-config.json
configs/openmrs/initializer_config/personattributetypes/personAttributeTypes.csv

Issue was discussed here:https://mekomsolutions.slack.com/archives/G421UNF5L/p1730882479524999

Added Email to person attribute types and fixed address line 2 translation

---

configs/openmrs/initializer_config/ampathforms/consultation_prenatale.json
configs/openmrs/initializer_config/ampathforms/depart_non_autorise.json
configs/openmrs/initializer_config/ampathforms/echographie_gynecologique.json
configs/openmrs/initializer_config/ampathforms/echographie_obstetricale_1.json
configs/openmrs/initializer_config/ampathforms/echographie_obstetricale_2.json
configs/openmrs/initializer_config/ampathforms/echographie_obstetricale_3.json
configs/openmrs/initializer_config/ampathforms/examen_des_systemes.json
configs/openmrs/initializer_config/ampathforms/examen_gynecologique.json
configs/openmrs/initializer_config/ampathforms/examen_obstetrical.json
configs/openmrs/initializer_config/ampathforms/examen_physique.json
configs/openmrs/initializer_config/ampathforms/historique_de_sante.json
configs/openmrs/initializer_config/ampathforms/motif_de_consultation.json
configs/openmrs/initializer_config/ampathforms/nutrition.json
configs/openmrs/initializer_config/ampathforms/reference.json
configs/openmrs/initializer_config/ampathforms/suivi_durgences.json
configs/openmrs/initializer_config/ampathforms/vaccinations.json

https://mekomsolutions.atlassian.net/browse/HSC-287

HSC-287: Updated form uuids

---

configs/openmrs/initializer_config/ampathforms/examen_gynecologique.json
configs/openmrs/initializer_config/ampathforms/historique_de_sante.json

https://mekomsolutions.atlassian.net/browse/HSC-287

HSC-287: Fixed missing concept 'Family History Set'.

---

configs/openmrs/initializer_config/ampathforms/vaccinations.json

https://mekomsolutions.atlassian.net/browse/HSC-287

HSC-287: Fixed missing vaccine lot number concept.

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Ticket here: https://mekomsolutions.atlassian.net/browse/HSC-367

HSC-367: Added Contact Person's Phone Number to patient banner

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Link to reference: https://github.com/openmrs/openmrs-esm-patient-management/blob/c4f9015d067e883c5d5ec218759846b8db0a9bf0/packages/esm-active-visits-app/src/config-schema.ts#L46

Adjusted count of active visits to be shown in a single page to 50

---

configs/openmrs/frontend_config/ozone-frontend-config.json

https://mekomsolutions.atlassian.net/browse/HSC-368

HSC-368: Add active visit obs config

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Link to the ticket: https://mekomsolutions.atlassian.net/browse/HSC-329
Related PR: https://github.com/openmrs/openmrs-esm-patient-chart/pull/2135
Related config point: https://github.com/openmrs/openmrs-esm-patient-chart/blob/c41e0187f434f46feb6ef0e67307c1e3763f65db/packages/esm-patient-banner-app/src/config-schema.ts#L48

(feat) Add the page size and print scale config for patient identifier sticker

---

configs/openmrs/frontend_config/ozone-frontend-config.json

https://mekomsolutions.atlassian.net/browse/HSC-363

HSC-363: Add `vitalSignsConceptSetUuid` config

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Link to the ticket: https://mekomsolutions.atlassian.net/browse/HSC-334

HSC-334: Add imaging and procedures order types

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Link to the ticket: https://mekomsolutions.atlassian.net/browse/HSC-329

HSC-329: Update the configuration for print identifier sticker functionality

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Ticket: https://mekomsolutions.atlassian.net/browse/HSC-293
[Screencast from 08-01-25 12:41:33.webm](https://github.com/user-attachments/assets/10e0160f-7f6a-4fa3-91b5-eac0d05efb01)
Replicating

HSC-293: Added life style obs-by-encounter-widget

---

configs/openmrs/frontend_config/ozone-frontend-config.json

https://mekomsolutions.atlassian.net/browse/HSC-312

HSC-312: Fixed config's French translations.

---

configs/openmrs/initializer_config/ampathformstranslations/vitals_and_biometrics_translations_en.json
configs/openmrs/initializer_config/ampathformstranslations/vitals_and_biometrics_translations_fr.json

Ticket: https://mekomsolutions.atlassian.net/browse/HSC-370
Attachemnets:
En ↓
Fr ↓

HSC-370: Add labels with units for weight, height, temperature, abnominal diameter, head circumference and mid-upper arm circumference

---

configs/openmrs/frontend_config/ozone-frontend-config.json

https://mekomsolutions.atlassian.net/browse/HSC-394

HSC-394: Remove Laboratory app + Add translation overrides for app navigation menu items

---

binaries/odoo/addons/stock_extension/__init__.py
binaries/odoo/addons/stock_extension/__manifest__.py
binaries/odoo/addons/stock_extension/models/__init__.py
binaries/odoo/addons/stock_extension/models/stock_production_lot.py
pom.xml
scripts/docker-compose-files.txt
scripts/docker-compose-override.yml

https://mekomsolutions.atlassian.net/browse/HSC-199

HSC-199: Added stock_extension addon and docker compose override file

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Link to the ticket: https://mekomsolutions.atlassian.net/browse/HSC-385

HSC-385: Hide reference fields for all order forms

---

configs/openmrs/frontend_config/ozone-frontend-config.json

https://mekomsolutions.atlassian.net/browse/HSC-395
Adjusting the translations in the config.

HSC-395: Adjust frontend config translations

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Fix the incorrectly formated Ozone frontend JSON file on the Ozone HSC.

(fix) Fix the Ozone Frontend Config JSON file

---

.github/workflows/ci.yml
pom.xml

This adds a profile to include Ozone Pro Features to the HSC Distro as part of https://mekomsolutions.atlassian.net/browse/HSC-350

HSC-350: Add Ozone Pro features to `ozone-hsc` distro

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Link to the ticket: https://mekomsolutions.atlassian.net/browse/HSC-397

HSC-397: Update the drug order type UUID

---

configs/openmrs/frontend_config/ozone-frontend-config.json

https://mekomsolutions.atlassian.net/browse/HSC-412
Adding Mother Name, Contact Person's Name, Contact Person's Phone Number, Contact Person Address, Contact Person Relationship to the patient contact details.

HSC-412: Add more person attributes on patient banner

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Link to the ticket: https://mekomsolutions.atlassian.net/browse/HSC-413

HSC-413: Move the lifestyle table into the patient chart summary dashboard

---

configs/openmrs/frontend_config/ozone-frontend-config.json

Ticket here: https://mekomsolutions.atlassian.net/browse/HSC-315?focusedCommentId=47022

HSC-315: Add order basket action menu

---

pom.xml

Adds the JMX exporter config file.

HSC-350: Add monitoring config

---

pom.xml
scripts/docker-compose-files.txt
scripts/docker-compose-odoo-override-sso.yml

Issue: https://mekomsolutions.atlassian.net/browse/HSC-350
This PR enables SSO in Ozone HSC via start scripts

HSC-350:  Enable SSO integration

---

README.md

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-340
This PR updates the README to match the Ozone's rebranding.

OZ-340: README as per Ozone's rebranding.

---

pom.xml

This adds that database creation script for Central auth.

HSC-350: Copy EIP Keycloak OpenMRS database creation script

---

pom.xml

https://mekomsolutions.atlassian.net/browse/HSC-350

HSC-350: Copy the full data directory from Ozone instead of only MySQL

---

configs/odoo/initializer_config/units_of_measure/product.uom.csv

JIRA: https://mekomsolutions.atlassian.net/browse/HSC-422

Add medical supply product UOMs

---

configs/odoo/initializer_config/units_of_measure/product.uom.csv

Reference: https://mekomsolutions.atlassian.net/browse/HSC-379?focusedCommentId=47297
Convo: https://mekomsolutions.slack.com/archives/G421UNF5L/p1740391150972249

Rename UOM `Kit -> Kit` and `Bag -> Sachet`

---

configs/openmrs/initializer_config/personattributetypes/void_email.csv

https://mekomsolutions.atlassian.net/browse/HSC-423

HSC-423: Void email field from Appointments module in favor of a known UUID

---

scripts/docker-compose-override.yml

Update the values needed buy the ERP modules to be Odoo credentials not DB credentials

Fix  ODOO_USER and ODOO_PASSWORD values

---

configs/openmrs/initializer_config/ampathforms/consultation_prenatale.json
configs/openmrs/initializer_config/ampathforms/echographie_obstetricale_1.json
configs/openmrs/initializer_config/ampathforms/echographie_obstetricale_2.json
configs/openmrs/initializer_config/ampathforms/echographie_obstetricale_3.json
configs/openmrs/initializer_config/ampathforms/emergency_department_form.json
configs/openmrs/initializer_config/ampathforms/examen_gynecologique.json
configs/openmrs/initializer_config/ampathforms/historique_de_sante.json
configs/openmrs/initializer_config/ampathforms/motif_de_consultation.json
configs/openmrs/initializer_config/ampathforms/nutrition.json
configs/openmrs/initializer_config/ampathforms/vaccinations.json
configs/openmrs/initializer_config/ampathforms/vitals_and_biometrics.json

JIRA: https://mekomsolutions.atlassian.net/browse/HSC-435

HSC-435: Fix the numeric fields in clinical forms

---

configs/openmrs/frontend_config/ozone-hsc-frontend-config.json

Issue: https://mekomsolutions.atlassian.net/browse/HSC-441
This PR removes password changer from user panel slot in primary navigation app

HSC-441: Remove password changer from user panel slot in primary navigation app

---

README.md

Ticket: https://mekomsolutions.atlassian.net/browse/HSC-382

HSC-382: Add release notes for version 2.0.0

---

configs/openmrs/frontend_config/ozone-hsc-frontend-config.json

JIRA: https://mekomsolutions.atlassian.net/browse/HSC-443

OZ-443: Add active medication and conditions in IPD summary page

---

configs/openmrs/frontend_config/ozone-hsc-frontend-config.json

JIRA: https://mekomsolutions.atlassian.net/browse/HSC-417

HSC-417: Set Indication to optional for drug orders

---

configs/openmrs/initializer_config/ampathforms/vitals_and_biometrics.json
configs/openmrs/initializer_config/ampathformstranslations/vitals_and_biometrics_translations_en.json
configs/openmrs/initializer_config/ampathformstranslations/vitals_and_biometrics_translations_fr.json

JIRA: https://mekomsolutions.atlassian.net/browse/HSC-370

HSC-370: Units of measurement to display in clinical forms for numeric fields in Vitals and Biometrics.

---

configs/openmrs/initializer_config/locations/locations.csv

Ticket: https://mekomsolutions.atlassian.net/browse/HSC-445
Attachment:
https://github.com/user-attachments/assets/fccdb383-7a9b-4de2-8d43-8f7864407aea

HSC-445: Update uuid for Administration location

---

configs/openmrs/initializer_config/patientidentifiertypes/facility_ids.csv

JIRA: https://mekomsolutions.atlassian.net/browse/LMP-6

LMP-6: Add `Numéro Dossier` identifier for Patient registration form

---

pom.xml

JIRA: https://mekomsolutions.atlassian.net/browse/HSC-478

HSC-478: Update Ozone version to `1.0.0-alpha.13`

---

pom.xml

JIRA: https://mekomsolutions.atlassian.net/browse/HSC-478

HSC-478: Change `ozone-pro` version to point to `1.0.0-alpha.14`

---

pom.xml
scripts/docker-compose-files.txt
scripts/docker-compose-odoo-override-sso.yml

Issue: https://mekomsolutions.atlassian.net/browse/HSC-483
This PR removes SSO related files & configs.

HSC-483: Remove SSO support

---

README.md

Ticket: https://mekomsolutions.atlassian.net/browse/HSC-528

HSC-528: Add release notes for v2.2.1
